# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a5feb77b11e73765daf6637cf933c00051a85b95e35ea60498f9cb79075ec95f410a60372f895fdef10efa55d1bbfab3635b32dc9d5b569688f55fe9f1c33f2

test:
  secret_key_base: 78106635b5b9003e03729c25f1c444991719d04ac1e36efdb14ef3ec67760065a43c3fd2d22d0d8b94f24e7986d29ebcd30c894d5ccaaee0736395ed1a21d9c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
